live_config_reload = true

[shell]
program = "/opt/homebrew/bin/tmux"
args = ["new-session", "-A", "-s", "0"]

[colors.cursor]
text = "#1E1E2E"
cursor = "#F5E0DC"

[colors.vi_mode_cursor]
text = "#1E1E2E"
cursor = "#B4BEFE"

[colors.search.matches]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.search.focused_match]
foreground = "#1E1E2E"
background = "#A6E3A1"

[colors.footer_bar]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.hints.start]
foreground = "#1E1E2E"
background = "#F9E2AF"

[colors.hints.end]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.selection]
text = "#1E1E2E"
background = "#F5E0DC"

# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
background = '#282828'
# soft contrast background = = '#32302f'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

[[colors.indexed_colors]]
index = 16
color = "#FAB387"

[[colors.indexed_colors]]
index = 17
color = "#F5E0DC"

[font]
size = 14

[font.bold]
family = "0xProto Nerd Font Propo"
style = "SemiBold"

[font.bold_italic]
family = "0xProto Nerd Font Propo"
style = "Medium Italic"

[font.italic]
family = "0xProto Nerd Font Propo"
style = "Italic"

[font.normal]
family = "0xProto Nerd Font Propo"
style = 'Regular'
# family = "JetBrainsMono Nerd Font"

[font.offset]
x = 0
y = 1

# T - Smart session manager
[[keyboard.bindings]]
chars = "\u0002T"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002J"
key = "J"
mods = "Command"

# Move up a pane
[[keyboard.bindings]]
chars = "\u0002\u001B[A"
key = "K"
mods = "Command|Shift"

# Move down a pane
[[keyboard.bindings]]
chars = "\u0002\u001B[B"
key = "J"
mods = "Command|Shift"

# Move left a pane
[[keyboard.bindings]]
chars = "\u0002\u001B[D"
key = "H"
mods = "Command|Shift"

# Move right a pane
[[keyboard.bindings]]
chars = "\u0002\u001B[C"
key = "L"
mods = "Command|Shift"

# Move to next window
[[keyboard.bindings]]
chars = "\u0002n"
key = "Comma"
mods = "Command"

# Move to prev window
[[keyboard.bindings]]
chars = "\u0002p"
key = "Period"
mods = "Command"

# New Window
[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Command"

# Close Window
[[keyboard.bindings]]
chars = "\u0002x"
key = "W"
mods = "Command"

# Split horizontally
[[keyboard.bindings]]
chars = "\u0002\""
key = "E"
mods = "Command"

# Split veritcally
[[keyboard.bindings]]
chars = "\u0002%"
key = "E"
mods = "Command|Shift"

# gh dash
[[keyboard.bindings]]
chars = "\u0002G"
key = "G"
mods = "Command"

[window]
decorations = "buttonless"
dynamic_padding = false
# opacity = 0.83

[window.padding]
x = 18
y = 16
