live_config_reload = true

[shell]
program = "/opt/homebrew/bin/tmux"
args = ["new-session", "-A", "-s", "0"]

[colors.primary]
background = "#1E1E2E"
foreground = "#CDD6F4"
dim_foreground = "#CDD6F4"
bright_foreground = "#CDD6F4"

[colors.cursor]
text = "#1E1E2E"
cursor = "#F5E0DC"

[colors.vi_mode_cursor]
text = "#1E1E2E"
cursor = "#B4BEFE"

[colors.search.matches]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.search.focused_match]
foreground = "#1E1E2E"
background = "#A6E3A1"

[colors.footer_bar]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.hints.start]
foreground = "#1E1E2E"
background = "#F9E2AF"

[colors.hints.end]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.selection]
text = "#1E1E2E"
background = "#F5E0DC"

[colors.normal]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#BAC2DE"

[colors.bright]
black = "#585B70"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#A6ADC8"

[colors.dim]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#BAC2DE"

[[colors.indexed_colors]]
index = 16
color = "#FAB387"

[[colors.indexed_colors]]
index = 17
color = "#F5E0DC"

[font]
size = 16

[font.bold]
family = "FiraCode Nerd Font"
style = "SemiBold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Medium Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = 'Regular'
# family = "CommitMono Nerd Font"

[font.offset]
x = 0
y = 1

# T - Smart session manager
[[keyboard.bindings]]
chars = "\u0002T"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002J"
key = "J"
mods = "Command"

# Move up a pane
[[keyboard.bindings]]
chars = "\u0002\u001B[A"
key = "K"
mods = "Command|Shift"

# Move down a pane
[[keyboard.bindings]]
chars = "\u0002\u001B[B"
key = "J"
mods = "Command|Shift"

# Move left a pane
[[keyboard.bindings]]
chars = "\u0002\u001B[D"
key = "H"
mods = "Command|Shift"

# Move right a pane
[[keyboard.bindings]]
chars = "\u0002\u001B[C"
key = "L"
mods = "Command|Shift"

# Move to next window
[[keyboard.bindings]]
chars = "\u0002n"
key = "Comma"
mods = "Command"

# Move to prev window
[[keyboard.bindings]]
chars = "\u0002p"
key = "Period"
mods = "Command"

# New Window
[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Command"

# Close Window
[[keyboard.bindings]]
chars = "\u0002x"
key = "W"
mods = "Command"

# Split horizontally
[[keyboard.bindings]]
chars = "\u0002\""
key = "E"
mods = "Command"

# Split veritcally
[[keyboard.bindings]]
chars = "\u0002%"
key = "E"
mods = "Command|Shift"

# gh dash
[[keyboard.bindings]]
chars = "\u0002G"
key = "G"
mods = "Command"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.87

[window.padding]
x = 18
y = 16
